steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - platform-core/api/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/bluewirks/api:v0.1.0
      - .
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/bluewirks/api:v0.1.0
